export default {
  USER_UPDATE: 'USER_UPDATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_TOKEN_UPDATE: 'USER_TOKEN_LOGIN',
  RESIZE: 'RESIZE',
  PRAYER: {
    ADD_PRAYER: 'PRAYER_ADD_PRAYER',
    ADD_INFOS: 'PRAYER_ADD_INFOS',
    ADD_NOTIF: 'PRAYER_ADD_NOTIFS',
    PRAYERS_ADD: 'PRAYERS_ADD',
    PRAYERS_UPDATE: 'PRAYERS_UPDATE',
    PRAYER_DELETE: 'PRAYERS_DELETE'
  },
}