export default {
  USER_UPDATE: 'USER_UPDATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_TOKEN_UPDATE: 'USER_TOKEN_LOGIN',
  USERS: {
    USERS_UPDATE: 'USERS_UPDATE',
    USERS_ADD: 'USERS_ADD',
    USERS_REMOVE: 'USERS_REMOVE',
  },
  RESIZE: 'RESIZE',
  PRAYER: {
    ADD_PRAYER: 'PRAYER_ADD_PRAYER',
    ADD_INFOS: 'PRAYER_ADD_INFOS',
    ADD_NOTIF: 'PRAYER_ADD_NOTIFS',
    PRAYERS_ADD: 'PRAYERS_ADD',
    PRAYERS_UPDATE: 'PRAYERS_UPDATE',
    PRAYER_DELETE: 'PRAYERS_DELETE',
    PRAYER_UPDATE: 'PRAYER_UPDATE',
  },
  INTENTIONS: {
    INT_UPDATE: 'INTENTIONS_UPDATE',
    INT_ADD: 'INTENTIONS_ADD',
    INT_DELETE: 'INTENTIONS_DELETE',
  },
  SNACKS: {
    ENQUEUE_SNACK: 'ENQUEUE_SNACK',
    CLOSE_SNACK: 'CLOSE_SNACK',
    REMOVE_SNACK: 'REMOVE_SNACK',
  },
}
